{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gooddaytaxi",
    "module": "common-core",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-core-0.0.1-SNAPSHOT.jar",
          "url": "common-core-0.0.1-SNAPSHOT.jar",
          "size": 6978,
          "sha512": "c9521be16eacbf146b9f03a00b4c2916650347ec0a9d14dee4a0aed4c71e6627aea1b72a11a49720f07cabf09550eae9ad49922c6d3e075c053d92695e94a059",
          "sha256": "7cc3b40b171de40db90afa68cdb11846f22444f541ec3744803c3a6a741bf66c",
          "sha1": "747d6eb144d01e59f8c5c7d0b5ce850018e6059d",
          "md5": "55043e170d4c99228e05ee988ff0713c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-0.0.1-SNAPSHOT.jar",
          "url": "common-core-0.0.1-SNAPSHOT.jar",
          "size": 6978,
          "sha512": "c9521be16eacbf146b9f03a00b4c2916650347ec0a9d14dee4a0aed4c71e6627aea1b72a11a49720f07cabf09550eae9ad49922c6d3e075c053d92695e94a059",
          "sha256": "7cc3b40b171de40db90afa68cdb11846f22444f541ec3744803c3a6a741bf66c",
          "sha1": "747d6eb144d01e59f8c5c7d0b5ce850018e6059d",
          "md5": "55043e170d4c99228e05ee988ff0713c"
        }
      ]
    }
  ]
}
