{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gooddaytaxi",
    "module": "common-jpa",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-jpa-0.0.5-SNAPSHOT.jar",
          "url": "common-jpa-0.0.5-SNAPSHOT.jar",
          "size": 2920,
          "sha512": "9b8172c976e1b0db2e4edbd63317092e7df3492f069c4b7c0e1131e41d5ac66d47992445efd67f904c720f5d3afd8e96f46ccace5bbe5251bda94878cc517d8b",
          "sha256": "d226dbfb995794059c9e49d8920b1c7a775706ae117bcdacc15761261631c06f",
          "sha1": "f66a6a19dde81c42bd0eef57197d641ba606ebf8",
          "md5": "0592ba744a434ff15988b41e06f04c32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gooddaytaxi",
          "module": "common-core",
          "version": {
            "requires": "0.0.5-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.5.2.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.querydsl",
          "module": "querydsl-jpa",
          "version": {
            "requires": "5.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "querydsl-jpa",
              "type": "jar",
              "extension": "jar",
              "classifier": "jakarta"
            }
          }
        }
      ],
      "files": [
        {
          "name": "common-jpa-0.0.5-SNAPSHOT.jar",
          "url": "common-jpa-0.0.5-SNAPSHOT.jar",
          "size": 2920,
          "sha512": "9b8172c976e1b0db2e4edbd63317092e7df3492f069c4b7c0e1131e41d5ac66d47992445efd67f904c720f5d3afd8e96f46ccace5bbe5251bda94878cc517d8b",
          "sha256": "d226dbfb995794059c9e49d8920b1c7a775706ae117bcdacc15761261631c06f",
          "sha1": "f66a6a19dde81c42bd0eef57197d641ba606ebf8",
          "md5": "0592ba744a434ff15988b41e06f04c32"
        }
      ]
    }
  ]
}
