{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gooddaytaxi",
    "module": "common-jpa",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-jpa-0.0.4-SNAPSHOT.jar",
          "url": "common-jpa-0.0.4-SNAPSHOT.jar",
          "size": 2920,
          "sha512": "fba94c8bc7051bc77608dd70edc7420921e341712fa3d03fb843853aedac6e862f3ea7674b7af766eaad54fbbb55a91cd4588a5156d47249ef26ecbbf7807906",
          "sha256": "6c9af3ca1aa25ea2bb2443af77a08a86a07955fd70f44d724ab8e00737593cae",
          "sha1": "9827fd982a57b9410eaee8baff8a7ab07ed9557f",
          "md5": "1066f610cafdaf027d968f0d77b36a81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.gooddaytaxi",
          "module": "common-core",
          "version": {
            "requires": "0.0.4-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.5.2.Final"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.querydsl",
          "module": "querydsl-jpa",
          "version": {
            "requires": "5.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "querydsl-jpa",
              "type": "jar",
              "extension": "jar",
              "classifier": "jakarta"
            }
          }
        }
      ],
      "files": [
        {
          "name": "common-jpa-0.0.4-SNAPSHOT.jar",
          "url": "common-jpa-0.0.4-SNAPSHOT.jar",
          "size": 2920,
          "sha512": "fba94c8bc7051bc77608dd70edc7420921e341712fa3d03fb843853aedac6e862f3ea7674b7af766eaad54fbbb55a91cd4588a5156d47249ef26ecbbf7807906",
          "sha256": "6c9af3ca1aa25ea2bb2443af77a08a86a07955fd70f44d724ab8e00737593cae",
          "sha1": "9827fd982a57b9410eaee8baff8a7ab07ed9557f",
          "md5": "1066f610cafdaf027d968f0d77b36a81"
        }
      ]
    }
  ]
}
