{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gooddaytaxi",
    "module": "common-core",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-core-0.0.5-SNAPSHOT.jar",
          "url": "common-core-0.0.5-SNAPSHOT.jar",
          "size": 6463,
          "sha512": "27220cd5aa40772a74df9d23e67a10a85a9c200670f4d39c1a5ff6c0849898ff356be194e75b25698944249d83537e9b7bb393ba77174438d22c150325e62988",
          "sha256": "7820fa1563fa96b1c9234fd69164d2c30fde2fe509391aa7e475a49915c7c262",
          "sha1": "acdb1774fafede05fc2822f25e076726455543e9",
          "md5": "6edc446a8b9c646f8c899c7583c38b11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-core-0.0.5-SNAPSHOT.jar",
          "url": "common-core-0.0.5-SNAPSHOT.jar",
          "size": 6463,
          "sha512": "27220cd5aa40772a74df9d23e67a10a85a9c200670f4d39c1a5ff6c0849898ff356be194e75b25698944249d83537e9b7bb393ba77174438d22c150325e62988",
          "sha256": "7820fa1563fa96b1c9234fd69164d2c30fde2fe509391aa7e475a49915c7c262",
          "sha1": "acdb1774fafede05fc2822f25e076726455543e9",
          "md5": "6edc446a8b9c646f8c899c7583c38b11"
        }
      ]
    }
  ]
}
